### ISSUE TITLE
jobsub commands hang when user needs to authenticate

### ISSUE THREAD

**Issue by retzkek** [marcmengel/jobsub_lite#110]
Running any jobsub or condor commands ~that point to jobsub_cmd~ (edit: every command actually) now seem to hang when the user doesn't have a valid token locally or in vault and needs to authenticate in the browser. It's not actually hanging, we're just not displaying the message that tells them to authenticate any more (#80).

https://github.com/marcmengel/jobsub_lite/blob/02c65037ef3096c3a3335136da749626d0a2d08c/lib/fake_ifdh.py#L123

Related, jobsub_cmd should have a --debug option (which it would get when changed to use `get_base_parser()` added in #73) and should pass that to the `get{Token,Proxy}()` functions.

**Comment by shreyb** [comment]
I'm going to split out the "related" comment, since the bug described in this issue is pretty urgent.

**Comment by shreyb** [comment]
Steps to reproduce:

1. Destroy all vault tokens `rm /tmp/vt*`
2. I happened to know I've never tried to submit jobs as the `gm2` experiment, so use them
3. Try jobsub_submit with gm2 as experiment:

```
# Works because --debug is turned on:
$ ./jobsub_lite/bin/jobsub_submit -G gm2 --resource-provides=usage_model=DEDICATED,OPPORTUNISTIC,OFFSITE --devserver  --debug 1  file:///usr/bin/printenv

Couldn't find a valid proxy.

PCI extension info:
 Path length: -1
 Policy language not specified.
 Policy file not specified.
Number of bits in key :2048
Files being used:
 CA certificate file: none
 Trusted certificates directory : /etc/grid-security/certificates
 Proxy certificate file : /tmp/x509up_gm2_Analysis_10610
 User certificate file: /tmp/x509up_u10610
 User key file: /tmp/x509up_u10610
Output to /tmp/x509up_gm2_Analysis_10610
Your identity: /DC=org/DC=cilogon/C=US/O=Fermi National Accelerator Laboratory/OU=People/CN=Shreyas Bhat/CN=UID:sbhat
Using configuration file /home/sbhat/.glite/vomses
Using configuration file /etc/vomses
Contacting  voms1.fnal.gov:15001 [/DC=org/DC=incommon/C=US/ST=Illinois/O=Fermi Research Alliance/OU=Fermilab/CN=voms1.fnal.gov] "fermilab" Done
Creating proxy to /tmp/x509up_gm2_Analysis_10610 ....................................................+++
.......................+++

No policy language specified, Gsi impersonation proxy assumed. Done


Warning: your certificate and proxy will expire Mon Sep  5 15:33:26 2022
which is within the requested lifetime of the proxy
Attempting OIDC authentication with https://fermicloud543.fnal.gov:8200

Complete the authentication at:
    https://cilogon.org/device/?user_code=3VQ-ZPN-2WC
No web open command defined, please copy/paste the above to any web browser
Waiting for response in web browser
^CRunning: voms-proxy-info -exists -valid 0:10 -file /tmp/x509up_gm2_Analysis_10610Running: {cmd}Running: htgettoken -a fermicloud543.fnal.gov -i gm2Traceback (most recent call last):
  File "./jobsub_lite/bin/jobsub_submit", line 240, in <module>
    main()
  File "./jobsub_lite/bin/jobsub_submit", line 175, in main
    proxy, token = get_creds(vars(args))
  File "/home/sbhat/jobsub_lite/lib/creds.py", line 31, in get_creds
    t = fake_ifdh.getToken(role, args.get("debug", 0))
  File "/home/sbhat/jobsub_lite/lib/fake_ifdh.py", line 127, in getToken
    raise PermissionError(f"Failed attempting '{cmd}'")
PermissionError: Failed attempting 'htgettoken -a fermicloud543.fnal.gov -i gm2 >&2'


# Fails ("Hangs", and I have to ctrl-c to get out)

[sbhat@fermicloud525 ~]$ ./jobsub_lite/bin/jobsub_submit -G gm2 --resource-provides=usage_model=DEDICATED,OPPORTUNISTIC,OFFSITE --devserver   file:///usr/bin/printenv
^CTraceback (most recent call last):
  File "./jobsub_lite/bin/jobsub_submit", line 240, in <module>
    main()
  File "./jobsub_lite/bin/jobsub_submit", line 175, in main
    proxy, token = get_creds(vars(args))
  File "/home/sbhat/jobsub_lite/lib/creds.py", line 31, in get_creds
    t = fake_ifdh.getToken(role, args.get("debug", 0))
  File "/home/sbhat/jobsub_lite/lib/fake_ifdh.py", line 127, in getToken
    raise PermissionError(f"Failed attempting '{cmd}'")
PermissionError: Failed attempting 'htgettoken -a fermicloud543.fnal.gov -i gm2 >/dev/null 2>&1'

```
