### ISSUE TITLE
how jobsub_q handles missing -G

### ISSUE THREAD

**Issue by rlcee** [marcmengel/jobsub_lite#122]
- if -G is not set, traceback is not expected
- old jobsub_q gives a reasonable response if -G is not set.

```
[rlc@fifeutilgpvm01 ~]$ jobsub_q
Traceback (most recent call last):
  File "/opt/jobsub_lite/bin/jobsub_q", line 114, in <module>
    main()
  File "/opt/jobsub_lite/bin/jobsub_q", line 64, in main
    f"{sys.argv[0]} needs -G group or $GROUP in the environment."
AttributeError: /opt/jobsub_lite/bin/jobsub_q needs -G group or $GROUP in the environment.

```

**Comment by marcmengel** [comment]
This was resolved by making the -G error raise SystemExit  instead of  KeyError; SystemExit does not print a stack trace.
