### ISSUE TITLE
X509_USER_PROXY override isn't working

### ISSUE THREAD

**Issue by shreyb** [marcmengel/jobsub_lite#132]
In DUNE's test, they see that setting the env `X509_USER_PROXY` doesn't actually set the proxy location - jobsub_lite still tries to get a new proxy:

```
+ export KRB5CCNAME=/tmp/krb5cc_poms_submit_dune
+ KRB5CCNAME=/tmp/krb5cc_poms_submit_dune
++ klist -kt /home/poms/private/keytabs/poms.keytab
++ tail -1
++ sed -e 's/.* //'
+ kinit -kt /home/poms/private/keytabs/poms.keytab poms/cd/pomsgpvm01.fnal.gov@FNAL.GOV
+ ssh -tx dunepro@fifeutilgpvm02.fnal.gov '
echo == process_id: $$ ==
export UPLOADS=/home/poms
export X509_USER_PROXY=/opt/dunepro/dunepro.Production.proxy
:
source /grid/fermiapp/products/common/etc/setups
setup poms_jobsub_wrapper -g poms41 -z /grid/fermiapp/products/common/db
. /grid/fermiapp/products/common/etc/setup; setup fife_utils; export HTGETTOKENOPTS="--credkey=dunepro/managedtokens/fifeutilgpvm02.fnal.gov"; unsetup jobsub_client; export JOBSUB_CLIENT_DIR=/opt/jobsub_lite/bin; export IFDH_TOKEN_ENABLE=1; setup -j ifdhc v2_6_6, -j ifdhc_config v2_6_6; export JOBSUB_CLIENT_DIR=/opt/jobsub_lite/bin; export BEARER_TOKEN_FILE=/tmp/token$$; export _condor_SEC_CREDENTIAL_STORER=/bin/true; htgettoken --nokerberos --nooidc -r production -i dune --credkey=dunepro/managedtokens/fifeutilgpvm01.fnal.gov -a fermicloud543.fnal.gov
UPS_OVERRIDE="" setup -j poms_jobsub_wrapper -g poms41 -z /grid/fermiapp/products/common/db, -j poms_client -g poms31 -z /grid/fermiapp/products/common/db
ups active
export POMS4_CAMPAIGN_STAGE_ID=14169
export POMS4_CAMPAIGN_STAGE_NAME="nvaughan-fifetutils_logon_test"
export POMS4_CAMPAIGN_STAGE_TYPE=regular
export POMS4_CAMPAIGN_ID=6290
export POMS4_CAMPAIGN_NAME="nvaughan-fifeutils_logon_test_production"
export POMS4_SUBMISSION_ID=1334877
export POMS4_CAMPAIGN_ID=6290
export POMS4_TEST_LAUNCH=False
export POMS_CAMPAIGN_ID=14169
export POMS_CAMPAIGN_NAME="nvaughan-fifeutils_logon_test_production__nvaughan-fifetutils_logon_test"
export POMS_PARENT_TASK_ID=
export POMS_TASK_ID=1334877
export POMS_LAUNCHER=nvaughan
export POMS_TEST=
export POMS_TASK_DEFINITION_ID=7090
export JOBSUB_GROUP=dune
fife_launch -c /home/dunepro/SAMtest/pomsdemo.cfg -Oglobal.tardir=/home/dunepro/SAMtest -Oglobal.tarname=may2022tutorial.tar.gz -Oglobal.fclfile=myana.fcl -Oglobal.outdir=/pnfs/dune/scratch/dunepro/fifeutilgpvm01_test -Oglobal.version=v09_48_01d00 -Osubmit.N=1 -Osubmit.expected-lifetime=5h -Osubmit.disk=10GB -Osubmit.memory=3000MB -Osubmit.devserver=True
echo == completed: $$ ==
exit
'
Pseudo-terminal will not be allocated because stdin is not a terminal.
== process_id: 16462 ==
Attempting to get token from https://fermicloud543.fnal.gov:8200 ... succeeded
Storing bearer token in /tmp/token16462
...
+ GROUP=dune
+ export GROUP
+ export SAM_EXPERIMENT=dune
+ SAM_EXPERIMENT=dune
+ export SAM_GROUP=dune
+ SAM_GROUP=dune
+ export SAM_STATION=dune
+ SAM_STATION=dune
+ export IFDH_CP_MAXRETRIES=2
+ IFDH_CP_MAXRETRIES=2
+ export XRD_CONNECTIONRETRY=32
+ XRD_CONNECTIONRETRY=32
+ export XRD_REQUESTTIMEOUT=14400
+ XRD_REQUESTTIMEOUT=14400
+ export XRD_REDIRECTLIMIT=255
+ XRD_REDIRECTLIMIT=255
+ export XRD_LOADBALANCERTTL=7200
+ XRD_LOADBALANCERTTL=7200
+ export XRD_STREAMTIMEOUT=7200
+ XRD_STREAMTIMEOUT=7200
+ export IFDH_TOKEN_ENABLE=1
+ IFDH_TOKEN_ENABLE=1
+ export IFDH_PROXY_ENABLE=0
+ IFDH_PROXY_ENABLE=0
+ jobsub_submit -e SAM_EXPERIMENT -e SAM_GROUP -e SAM_STATION -e IFDH_CP_MAXRETRIES -e XRD_CONNECTIONRETRY -e XRD_REQUESTTIMEOUT -e XRD_REDIRECTLIMIT -e XRD_LOADBALANCERTTL -e XRD_STREAMTIMEOUT -e IFDH_TOKEN_ENABLE -e IFDH_PROXY_ENABLE -G dune -N 1 --resource-provides=usage_model=OPPORTUNISTIC,DEDICATED,OFFSITE --memory=3000MB --cpu=1 --disk=10GB --expected-lifetime=5h '--append_condor_requirements=(TARGET.HAS_Singularity==true&&TARGET.HAS_CVMFS_dune_opensciencegrid_org==true&&TARGET.HAS_CVMFS_larsoft_opensciencegrid_org==true&&TARGET.CVMFS_dune_opensciencegrid_org_REVISION>=1105&&TARGET.HAS_CVMFS_fifeuser1_opensciencegrid_org==true&&TARGET.HAS_CVMFS_fifeuser2_opensciencegrid_org==true&&TARGET.HAS_CVMFS_fifeuser3_opensciencegrid_org==true&&TARGET.HAS_CVMFS_fifeuser4_opensciencegrid_org==true)' '--lines=+SingularityImage=\"/cvmfs/singularity.opensciencegrid.org/fermilab/fnal-wn-sl7:latest\"' --lines=+FERMIHTC_AutoRelease=True --lines=+FERMIHTC_GraceMemory=2000 --lines=+FERMIHTC_GraceLifetime=86400 --tar_file_name=dropbox:///home/dunepro/SAMtest/may2022tutorial.tar.gz --role=Production --devserver file://///grid/fermiapp/products/common/db/../prd/fife_utils/v3_5_0/NULL/libexec/fife_wrap --find_setups --source-unquote %24%7BINPUT_TAR_DIR_LOCAL%7D/setupMay2022Tutorial-grid.sh --prescript-unquote cd%20%24%7B_CONDOR_JOB_IWD%7D --prescript-unquote ln%20-s%20%24%7BINPUT_TAR_DIR_LOCAL%7D/may2022tutorial/work/myana.fcl%20. --export-unquote FILETIMESTAMP%3D%24%28date%20-u%20%2B%25Y%25m%25dT%25H%25M%25SZ%29 --limit 1 --schema root --appvers v09_48_01d00 --addoutput 'tutorial_hist_*.root' --dest /pnfs/dune/scratch/dunepro/fifeutilgpvm01_test --metadata_extractor json --exe lar -- -c myana.fcl -n 2 -T 'tutorial_hist_${CLUSTER}_${PROCESS}_\\\${FILETIMESTAMP}.root' root://fndca1.fnal.gov:1094/pnfs/fnal.gov/usr/dune/tape_backed/dunepro/protodune-sp/full-reconstructed/2021/mc/out1/PDSPProd4a/18/80/01/67/PDSPProd4a_protoDUNE_sp_reco_stage1_p1GeV_35ms_sce_datadriven_18800167_0_20210414T002116Z.root
WARNING:root:Notice: poms_client.get_task_id_for() is deprecated, use get_submission_id
Traceback (most recent call last):
  File "/opt/jobsub_lite/bin/jobsub_submit", line 240, in 
    main()
  File "/opt/jobsub_lite/bin/jobsub_submit", line 175, in main
    proxy, token = get_creds(vars(args))
  File "/opt/jobsub_lite/lib/creds.py", line 30, in get_creds
    p = fake_ifdh.getProxy(role, args.get("debug", 0))
  File "/opt/jobsub_lite/lib/fake_ifdh.py", line 186, in getProxy
    raise PermissionError(f"Failed attempting '{cmd}'")
PermissionError: Failed attempting 'voms-proxy-init -dont-verify-ac -valid 120:00 -rfc -noregen -debug -cert /tmp/x509up_u50762 -key /tmp/x509up_u50762 -out /tmp/x509up_dune_Production_50762 -voms dune:/dune/Role=Production > /dev/null 2>&1'
...
```

**Comment by shreyb** [comment]
Have a fix in, validated with test:

```
[dunepro@fermicloud525 ~]$ export HTGETTOKENOPTS="--credkey=dunepro/managedtokens/fifeutilgpvm01.fnal.gov"
[dunepro@fermicloud525 ~]$ export X509_USER_PROXY=/tmp/dunepro.Production.proxy
[dunepro@fermicloud525 ~]$    ~sbhat/jobsub_lite/bin/jobsub_submit -G dune --role=production  --resource-provides=usage_model=DEDICATED,OPPORTUNISTIC,OFFSITE --verbose file:///usr/bin/printenv
proxy is : /tmp/dunepro.Production.proxy
token is : /tmp/bt_token_dune_production_50762
classads:  [[ AddressV1 = "{[ p=\"primary\"; a=\"131.225.161.93\"; port=9615; n=\"Internet\"; alias=\"jobsub01.fnal.gov\"; spid=\"schedd_3232_762e\"; noUDP=true; ], [ p=\"IPv4\"; a=\"131.225.161.93\"; port=9615; n=\"Internet\"; alias=\"jobsub01.fnal.gov\"; spid=\"schedd_3232_762e\"; noUDP=true; ], [ p=\"IPv6\"; a=\"2620:6a:0:430:f0:0:161:93\"; port=9615; n=\"Internet\"; alias=\"jobsub01.fnal.gov\"; spid=\"schedd_3232_762e\"; noUDP=true; ]}"; CondorPlatform = "$CondorPlatform: x86_64_CentOS7 $"; CondorVersion = "$CondorVersion: 9.0.16 Aug 16 2022 BuildID: 601457 PackageID: 9.0.16-1 $"; Machine = "jobsub01.fnal.gov"; MyAddress = "<131.225.161.93:9615?addrs=131.225.161.93-9615+[2620-6a-0-430-f0-0-161-93]-9615&alias=jobsub01.fnal.gov&noUDP&sock=schedd_3232_762e>"; Name = "jobsub01.fnal.gov" ], [ AddressV1 = "{[ p=\"primary\"; a=\"131.225.240.53\"; port=9615; n=\"Internet\"; alias=\"jobsub03.fnal.gov\"; spid=\"schedd_2696_cf6b\"; noUDP=true; ], [ p=\"IPv4\"; a=\"131.225.240.53\"; port=9615; n=\"Internet\"; alias=\"jobsub03.fnal.gov\"; spid=\"schedd_2696_cf6b\"; noUDP=true; ]}"; CondorPlatform = "$CondorPlatform: x86_64_CentOS7 $"; CondorVersion = "$CondorVersion: 9.0.14 Jul 12 2022 BuildID: 595707 PackageID: 9.0.14-1 $"; Machine = "jobsub03.fnal.gov"; MyAddress = "<131.225.240.53:9615?addrs=131.225.240.53-9615&alias=jobsub03.fnal.gov&noUDP&sock=schedd_2696_cf6b>"; Name = "jobsub03.fnal.gov" ], [ AddressV1 = "{[ p=\"primary\"; a=\"131.225.161.104\"; port=9615; n=\"Internet\"; alias=\"jobsub02.fnal.gov\"; spid=\"schedd_3316_1423\"; noUDP=true; ], [ p=\"IPv4\"; a=\"131.225.161.104\"; port=9615; n=\"Internet\"; alias=\"jobsub02.fnal.gov\"; spid=\"schedd_3316_1423\"; noUDP=true; ]}"; CondorPlatform = "$CondorPlatform: x86_64_CentOS7 $"; CondorVersion = "$CondorVersion: 9.0.14 Jul 12 2022 BuildID: 595707 PackageID: 9.0.14-1 $"; Machine = "jobsub02.fnal.gov"; MyAddress = "<131.225.161.104:9615?addrs=131.225.161.104-9615&alias=jobsub02.fnal.gov&noUDP&sock=schedd_3316_1423>"; Name = "jobsub02.fnal.gov" ], [ AddressV1 = "{[ p=\"primary\"; a=\"131.225.161.91\"; port=9618; n=\"Internet\"; alias=\"gpce03.fnal.gov\"; spid=\"schedd_3379_4a9a\"; noUDP=true; ], [ p=\"IPv4\"; a=\"131.225.161.91\"; port=9618; n=\"Internet\"; alias=\"gpce03.fnal.gov\"; spid=\"schedd_3379_4a9a\"; noUDP=true; ]}"; CondorPlatform = "$CondorPlatform: x86_64_CentOS7 $"; CondorVersion = "$CondorVersion: 9.0.14 Jul 12 2022 BuildID: 595707 PackageID: 9.0.14-1 $"; Machine = "gpce03.fnal.gov"; MyAddress = "<131.225.161.91:9618?addrs=131.225.161.91-9618&alias=gpce03.fnal.gov&noUDP&sock=schedd_3379_4a9a>"; Name = "gpce03.fnal.gov" ], [ AddressV1 = "{[ p=\"primary\"; a=\"131.225.240.23\"; port=9615; n=\"Internet\"; alias=\"jobsubdevgpvm01.fnal.gov\"; spid=\"schedd_2683_e4b0\"; noUDP=true; ], [ p=\"IPv4\"; a=\"131.225.240.23\"; port=9615; n=\"Internet\"; alias=\"jobsubdevgpvm01.fnal.gov\"; spid=\"schedd_2683_e4b0\"; noUDP=true; ]}"; CondorPlatform = "$CondorPlatform: x86_64_CentOS7 $"; CondorVersion = "$CondorVersion: 9.0.16 Aug 16 2022 BuildID: 601457 PackageID: 9.0.16-1 $"; Machine = "jobsubdevgpvm01.fnal.gov"; MyAddress = "<131.225.240.23:9615?addrs=131.225.240.23-9615&alias=jobsubdevgpvm01.fnal.gov&noUDP&sock=schedd_2683_e4b0>"; Name = "jobsubdevgpvm01.fnal.gov" ], [ AddressV1 = "{[ p=\"primary\"; a=\"131.225.161.26\"; port=9618; n=\"Internet\"; alias=\"gpce04.fnal.gov\"; spid=\"schedd_3384_b893\"; noUDP=true; ], [ p=\"IPv4\"; a=\"131.225.161.26\"; port=9618; n=\"Internet\"; alias=\"gpce04.fnal.gov\"; spid=\"schedd_3384_b893\"; noUDP=true; ]}"; CondorPlatform = "$CondorPlatform: x86_64_CentOS7 $"; CondorVersion = "$CondorVersion: 9.0.14 Jul 12 2022 BuildID: 595707 PackageID: 9.0.14-1 $"; Machine = "gpce04.fnal.gov"; MyAddress = "<131.225.161.26:9618?addrs=131.225.161.26-9618&alias=gpce04.fnal.gov&noUDP&sock=schedd_3384_b893>"; Name = "gpce04.fnal.gov" ]]
Submitting job(s).
1 job(s) submitted to cluster 57106741.
Use job id 57106741.0@jobsub01.fnal.gov to retrieve output
```

Running unit tests before opening PR.

**Comment by shreyb** [comment]
After discussion with @marcmengel , I realized that I've made the fix in the wrong place - that is, I made an assumption that the env setting pointed to an existing file, which we can't assume.  Changed this, and tested:

```
[dunepro@fermicloud525 tmp]$    ~sbhat/jobsub_lite/bin/jobsub_submit -G dune --role=production  --resource-provides=usage_model=DEDICATED,OPPORTUNISTIC,OFFSITE --verbose file:///usr/bin/printenv
Attempting to get token from https://fermicloud543.fnal.gov:8200 ... succeeded
Storing bearer token in /tmp/bt_token_dune_production_50762
proxy is : /tmp/dunepro.Production.proxy
token is : /tmp/bt_token_dune_production_50762
classads:  [[ AddressV1 = "{[ p=\"primary\"; a=\"131.225.161.93\"; port=9615; n=\"Internet\"; alias=\"jobsub01.fnal.gov\"; spid=\"schedd_3232_762e\"; noUDP=true; ], [ p=\"IPv4\"; a=\"131.225.161.93\"; port=9615; n=\"Internet\"; alias=\"jobsub01.fnal.gov\"; spid=\"schedd_3232_762e\"; noUDP=true; ], [ p=\"IPv6\"; a=\"2620:6a:0:430:f0:0:161:93\"; port=9615; n=\"Internet\"; alias=\"jobsub01.fnal.gov\"; spid=\"schedd_3232_762e\"; noUDP=true; ]}"; CondorPlatform = "$CondorPlatform: x86_64_CentOS7 $"; CondorVersion = "$CondorVersion: 9.0.16 Aug 16 2022 BuildID: 601457 PackageID: 9.0.16-1 $"; Machine = "jobsub01.fnal.gov"; MyAddress = "<131.225.161.93:9615?addrs=131.225.161.93-9615+[2620-6a-0-430-f0-0-161-93]-9615&alias=jobsub01.fnal.gov&noUDP&sock=schedd_3232_762e>"; Name = "jobsub01.fnal.gov" ], [ AddressV1 = "{[ p=\"primary\"; a=\"131.225.240.53\"; port=9615; n=\"Internet\"; alias=\"jobsub03.fnal.gov\"; spid=\"schedd_2696_cf6b\"; noUDP=true; ], [ p=\"IPv4\"; a=\"131.225.240.53\"; port=9615; n=\"Internet\"; alias=\"jobsub03.fnal.gov\"; spid=\"schedd_2696_cf6b\"; noUDP=true; ]}"; CondorPlatform = "$CondorPlatform: x86_64_CentOS7 $"; CondorVersion = "$CondorVersion: 9.0.14 Jul 12 2022 BuildID: 595707 PackageID: 9.0.14-1 $"; Machine = "jobsub03.fnal.gov"; MyAddress = "<131.225.240.53:9615?addrs=131.225.240.53-9615&alias=jobsub03.fnal.gov&noUDP&sock=schedd_2696_cf6b>"; Name = "jobsub03.fnal.gov" ], [ AddressV1 = "{[ p=\"primary\"; a=\"131.225.161.104\"; port=9615; n=\"Internet\"; alias=\"jobsub02.fnal.gov\"; spid=\"schedd_3316_1423\"; noUDP=true; ], [ p=\"IPv4\"; a=\"131.225.161.104\"; port=9615; n=\"Internet\"; alias=\"jobsub02.fnal.gov\"; spid=\"schedd_3316_1423\"; noUDP=true; ]}"; CondorPlatform = "$CondorPlatform: x86_64_CentOS7 $"; CondorVersion = "$CondorVersion: 9.0.14 Jul 12 2022 BuildID: 595707 PackageID: 9.0.14-1 $"; Machine = "jobsub02.fnal.gov"; MyAddress = "<131.225.161.104:9615?addrs=131.225.161.104-9615&alias=jobsub02.fnal.gov&noUDP&sock=schedd_3316_1423>"; Name = "jobsub02.fnal.gov" ], [ AddressV1 = "{[ p=\"primary\"; a=\"131.225.161.91\"; port=9618; n=\"Internet\"; alias=\"gpce03.fnal.gov\"; spid=\"schedd_3379_4a9a\"; noUDP=true; ], [ p=\"IPv4\"; a=\"131.225.161.91\"; port=9618; n=\"Internet\"; alias=\"gpce03.fnal.gov\"; spid=\"schedd_3379_4a9a\"; noUDP=true; ]}"; CondorPlatform = "$CondorPlatform: x86_64_CentOS7 $"; CondorVersion = "$CondorVersion: 9.0.14 Jul 12 2022 BuildID: 595707 PackageID: 9.0.14-1 $"; Machine = "gpce03.fnal.gov"; MyAddress = "<131.225.161.91:9618?addrs=131.225.161.91-9618&alias=gpce03.fnal.gov&noUDP&sock=schedd_3379_4a9a>"; Name = "gpce03.fnal.gov" ], [ AddressV1 = "{[ p=\"primary\"; a=\"131.225.240.23\"; port=9615; n=\"Internet\"; alias=\"jobsubdevgpvm01.fnal.gov\"; spid=\"schedd_2683_e4b0\"; noUDP=true; ], [ p=\"IPv4\"; a=\"131.225.240.23\"; port=9615; n=\"Internet\"; alias=\"jobsubdevgpvm01.fnal.gov\"; spid=\"schedd_2683_e4b0\"; noUDP=true; ]}"; CondorPlatform = "$CondorPlatform: x86_64_CentOS7 $"; CondorVersion = "$CondorVersion: 9.0.16 Aug 16 2022 BuildID: 601457 PackageID: 9.0.16-1 $"; Machine = "jobsubdevgpvm01.fnal.gov"; MyAddress = "<131.225.240.23:9615?addrs=131.225.240.23-9615&alias=jobsubdevgpvm01.fnal.gov&noUDP&sock=schedd_2683_e4b0>"; Name = "jobsubdevgpvm01.fnal.gov" ], [ AddressV1 = "{[ p=\"primary\"; a=\"131.225.161.26\"; port=9618; n=\"Internet\"; alias=\"gpce04.fnal.gov\"; spid=\"schedd_3384_b893\"; noUDP=true; ], [ p=\"IPv4\"; a=\"131.225.161.26\"; port=9618; n=\"Internet\"; alias=\"gpce04.fnal.gov\"; spid=\"schedd_3384_b893\"; noUDP=true; ]}"; CondorPlatform = "$CondorPlatform: x86_64_CentOS7 $"; CondorVersion = "$CondorVersion: 9.0.14 Jul 12 2022 BuildID: 595707 PackageID: 9.0.14-1 $"; Machine = "gpce04.fnal.gov"; MyAddress = "<131.225.161.26:9618?addrs=131.225.161.26-9618&alias=gpce04.fnal.gov&noUDP&sock=schedd_3384_b893>"; Name = "gpce04.fnal.gov" ]]
Submitting job(s).
1 job(s) submitted to cluster 57106742.
Use job id 57106742.0@jobsub01.fnal.gov to retrieve output
```
