### ISSUE TITLE
jobsub_lite jobsub_submit -f dropbox error

### ISSUE THREAD

**Issue by shreyb** [marcmengel/jobsub_lite#161]
Copied from Herb Greenlee ticket in ServiceNow (INC000001143396)

Outage start date: 2022-11-22 10:11:58 (US/Central)
Outage/Incident details:
Testing jobsub_lite on fifeutilgpvm02.

fifeutilgpvm02:~ $ which jobsub_submit
/opt/jobsub_lite/bin/jobsub_submit

fifeutilgpvm02:~ $ jobsub_submit -G uboone -f dropbox:///home/greenlee/test3.dat file:///home/greenlee/bin/testbatch.sh
tar (child): ///home/greenlee.tar.gz: Cannot open: Permission denied
tar (child): Error is not recoverable: exiting now
test3.dat
tar: ///home/greenlee.tar.gz: Cannot write: Broken pipe
tar: Error is not recoverable: exiting now
Traceback (most recent call last):
  File "/opt/jobsub_lite/bin/jobsub_submit", line 237, in <module>
    main()
  File "/opt/jobsub_lite/bin/jobsub_submit", line 173, in main
    do_tarballs(args)
  File "/opt/jobsub_lite/lib/tarfiles.py", line 106, in do_tarballs
    path = tarfile_in_dropbox(args, tarfile)
  File "/opt/jobsub_lite/lib/tarfiles.py", line 157, in tarfile_in_dropbox
    digest, tf = slurp_file(tfn)
  File "/opt/jobsub_lite/lib/tarfiles.py", line 62, in slurp_file
    with open(fname, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: '///home/greenlee.tar.gz'

**Comment by shreyb** [comment]
Found the issue.  For a `-f dropbox://` URI, on this line:  https://github.com/marcmengel/jobsub_lite/blob/master/lib/tarfiles.py#L100, we shorten the argument to drop the `dropbox:` bit.  So in Herb's case, 

```-f dropbox:///home/greenlee/test3.dat``` 

became 

```///home/greenlee/test3.dat```

We then pass `os.path.dirname("///home/greenlee/test3.dat") as the `directory` argument to `tar_up()`.  That evaluates to `directory = "///home/greenlee"`.  Still OK, but actually, I think this creates an incompatibility with old jobsub.  But we'll address that in a bit.

The problem is that `tar_up` tries to create a tarball called `///home/greenlee.tar.gz`, which, of course, it can't, because the `greenlee` user can't write inside `/home/`.  See https://github.com/marcmengel/jobsub_lite/blob/master/lib/tarfiles.py#L50 and https://github.com/marcmengel/jobsub_lite/blob/master/lib/tarfiles.py#L54

The other issue, compatibility-wise, is that in old jobsub, I think we wouldn't have named that tarball `///home/greenlee.tar.gz`, but rather `${CWD}/test3.tar.gz`.  That is, we would have stripped the suffix from the filename, and named the tarball after that.  I propose here that we do the same, and it'd involve a change to the wrapper scripts.

Since it's Thanksgiving week, we won't rush this immediately, but post-Thanksgiving, this should be addressed as close-to-the-top priority.  But big thanks to Herb for finding this bug in testing.
