### ISSUE TITLE
bare condor_submit should return help, not a traceback

### ISSUE THREAD

**Issue by retzkek** [marcmengel/jobsub_lite#21]
```
$ condor_submit
Traceback (most recent call last):
  File "/opt/jobsub_lite/bin/condor_submit", line 83, in <module>
    main()
  File "/opt/jobsub_lite/bin/condor_submit", line 71, in main
    proxy, token = get_creds(args)
NameError: name 'args' is not defined
```

**Comment by retzkek** [comment]
Sorry for the duplicate I'll just close this then.
