### ISSUE TITLE
jobsub_submit --maxConcurrent crash 

### ISSUE THREAD

**Issue by retzkek** [marcmengel/jobsub_lite#259]
It's trying to use `varg["dest"]` which is not defined; I'm not exactly sure what that should be?

```
$ jobsub_submit -G fermilab -n -N 1000 --maxConcurrent 10 file:///bin/true
Traceback (most recent call last):
  File "/opt/jobsub_lite/bin/jobsub_submit", line 309, in <module>
    main()
  File "/opt/jobsub_lite/bin/jobsub_submit", line 290, in main
    render_files(d1, varg, submitdir, dlist=[d1, d2, varg["dest"]])
KeyError: 'dest'
```

**Comment by marcmengel** [comment]
Should be `varg["outdir"] `or `submitdir`...

**Comment by retzkek** [comment]
I figured from the other DAG routines. So this is an interesting message (after fixing that):

```
 $ bin/jobsub_submit -G fermilab -N 10 --maxConcurrent 1 file:///home/kretzke/testinfo.sh                             

-----------------------------------------------------------------------
File for submitting this DAG to HTCondor           : /home/kretzke/.cache/jobsub_lite/js_2023_02_02_142219_820e3e87-aa4c-4526-9782-3a7c47aa45a3/maxconcurrent.d
ag.condor.sub
Log of DAGMan debugging messages                 : /home/kretzke/.cache/jobsub_lite/js_2023_02_02_142219_820e3e87-aa4c-4526-9782-3a7c47aa45a3/maxconcurrent.dag
.dagman.out
Log of HTCondor library output                     : /home/kretzke/.cache/jobsub_lite/js_2023_02_02_142219_820e3e87-aa4c-4526-9782-3a7c47aa45a3/maxconcurrent.d
ag.lib.out
Log of HTCondor library error messages             : /home/kretzke/.cache/jobsub_lite/js_2023_02_02_142219_820e3e87-aa4c-4526-9782-3a7c47aa45a3/maxconcurrent.d
ag.lib.err
Log of the life of condor_dagman itself          : /home/kretzke/.cache/jobsub_lite/js_2023_02_02_142219_820e3e87-aa4c-4526-9782-3a7c47aa45a3/maxconcurrent.dag
.dagman.log

-no_submit given, not submitting DAG to HTCondor.  You can do this with:
"condor_submit /home/kretzke/.cache/jobsub_lite/js_2023_02_02_142219_820e3e87-aa4c-4526-9782-3a7c47aa45a3/maxconcurrent.dag.condor.sub"
-----------------------------------------------------------------------
Submitting job(s).
1 job(s) submitted to cluster 57114838.
```

Seems we need to squelch the output of `condor_submit_dag`?

**Comment by marcmengel** [comment]
We shouldn't be *calling* condor_submit_dag... that should only get called if there is no submit file in the template directory, or it doesn't get rendered...
