### ISSUE TITLE
Ok, so now I can't see other user's log files at all.  this is going to make debugging hard. 

### ISSUE THREAD

**Issue by hschellman** [marcmengel/jobsub_lite#291]
I'm trying to help a user debug their tarball workflow and now I can't:

<schellma> jobsub_fetchlog -G minerva  --jobid=57358525.0@jobsub01.fnal.gov
Traceback (most recent call last):
  File "/opt/jobsub_lite/bin/jobsub_fetchlog", line 164, in <module>
    main()
  File "/opt/jobsub_lite/bin/jobsub_fetchlog", line 111, in main
    os.stat(iwd)
PermissionError: [Errno 13] Permission denied: '/nashome/s/sultana/.cache/jobsub_lite/js_2023_02_21_115244_3d07afd4-c43f-435d-b859-8afd376b2623'

**Comment by shreyb** [comment]
This will be fixed when all of the monitoring bits are put in place.  The jobsub_lite portion of it (#255) will be released in 1.1, on Thursday (I'm about to send out an announcement email about it), and the landscape side will be rolled out over the next few days.

**Comment by shreyb** [comment]
Assigning to @retzkek so he can let @hschellman know when to test this access.  

Note that the following works in ITB (requires FNAL VPN access):

https://landscapeitb.fnal.gov/lens/view/job/57358525.0@jobsub01.fnal.gov/

But as Kevin tweaks things, it may not STAY working while he finalizes the rollout plan to production.

**Comment by retzkek** [comment]
Web logs are now fully in production, logs for jobs _submitted_ with v1.1 or later are now available in landscape, e.g. for a recent dune user job: https://landscape.fnal.gov/lens/view/job/57392015.92@jobsub01.fnal.gov/

There's also a token-friendly endpoint, if you hate web browsers and would rather use the command line (while we work on getting jobsub_fetchlog changed to use it):
```
$ htgettoken -a htvaultprod.fnal.gov -i dune
...
Storing bearer token in /run/user/50216/bt_u50216

$ curl -s -H "Authorization: Bearer $(cat /run/user/50216/bt_u50216)" \
https://landscape.fnal.gov/fetchlog/job/57392015.92@jobsub01.fnal.gov/stdout | head
Mon Feb 27 17:37:32 UTC 2023 57392015.92@jobsub01.fnal.gov BEGIN EXECUTION sub_dirFit9.sh 0 PROD21
...
```
